title: Tailwindcss Testing
# email:
# description:
baseurl: "Tailwindcss-Test"
url: "https://alliegaytor.github.io/Tailwindcss-Test/"

# Build settings
plugins:
  - jekyll-postcss-v2


postcss:
  script: node_modules/.bin/postcss
  config: postcss.config.js

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - postcss.config.js
  - tailwind.config.js
  - package*.json